# Choose Mode:
# 1 : Download Sub
# 2 : Change Time
# 3 : Translate

#Type
# 1 : Movies
# 2 : TV-Shows

# Note : Please rename this file into config.yaml

MODE: # fill with int value. example: 1 -> means just download the subtitle from opensubtitles.com
TYPE: 1 # means movies

# Fill if you are using MODE = 1
USERNAME: "<your username in opensubtitles.com>"
PASSWORD: "<your password in opensubtitles.com>"

#Type Movies
IMDB_ID_MOVIES: [tt10574558]

# Type TV Show
IMDB_ID_TV_SHOW: [tt9612982,tt13446168] # example: https://www.imdb.com/title/tt26628595/ your id is : tt26628595
SEASON: # input tv-show season (int) example: 1
FROM_EPISODE: # input tv-show (episode) example: 1
TO_EPISODE: # input tv-show (episode) if just one episode fill same with <from episode> example: 1

# Resync The Subtitle Time
CHANGE_TIME:
  MILLISECOND: # Fill with int value. example: 1000 -> it means 1 second

# Translate the Subtitle
TRANSLATE:
  LLM_MODEL: llama3
  LLM_URL: http://localhost:11434/api/generate
  TARGET_LANGUAGE: id # get know you language support here https://cloud.google.com/translate/docs/languages

